### ISSUE TITLE
Website broken

### ISSUE THREAD

**Issue by tom25519** [keybase/saltpack#92] opened 2022-10-10 22:05 UTC
Hi, the saltpack.org website appears to be broken in its current state. The [homepage](https://saltpack.org/) and pages listed under the "Basics" menu all work, but the spec details (e.g: [Encryption](https://saltpack.org/encryption-format-v2), [Signing](https://saltpack.org/signing-format-v2)) display "Error: Couldn't load /home/keybase/src/keybase/saltpack.org/views/doc_symlink/saltpack_signing_v2.md" (or whatever page should be shown).

**Comment by prologic** [comment] 2022-10-10 22:23
I can confirm

**Comment by jphastings** [comment] 2022-11-15 22:27
I came here to post this same issue. To the maintainers: is there any way we can help?

**Comment by prologic** [comment] 2022-11-15 22:35
I'm not sure that Keybase really exists anymore since Zoom bought them out. I'd probably find the source code to the website (if available) and fork it and publish it ourselves somewhere. I'm using the Saltpack format in a few of my projects so I have a vested interest in seeing the spec/format maintained somewhere 👌

**Comment by jphastings** [comment] 2022-11-20 08:41
@prologic - looks like it's provided under [BSD-3](https://github.com/keybase/saltpack/blob/master/LICENSE) so that could definitely be done, with some limitations. If you wanted to fork the whole thing under a new github org and maintain it I'd be willing to help (and even buy/maintain saltpack dot net…).

**Comment by prologic** [comment] 2022-11-20 10:15
> @prologic - looks like it's provided under [BSD-3](https://github.com/keybase/saltpack/blob/master/LICENSE) so that could definitely be done, with some limitations. If you wanted to fork the whole thing under a new github org and maintain it I'd be willing to help (and even buy/maintain saltpack dot net…).
> 
> (However the site doesn't appear to be open source; I'd be happy to help build another)

Let's do this! 👌 As I said I have a vested interest in this as I'm the founder of [Salty IM](https://salty.im) that heavily uses and relies on the Saltpack format/sepc. Feel free to reach out to me (_I'm not that hard to find online 🤣_)

**Comment by joshblum** [comment] 2022-12-06 20:52
@tom25519 thanks for reporting, this is now fixed

**Closed by joshblum** 2022-12-06 20:52 UTC

**Comment by prologic** [comment] 2022-12-06 23:43
Thanks [joshblum](https://github.com/joshblum) 👌
